export default [
  { name: 'Charlie', surname: 'D Amelio', alias: 'CD', occupation: 'agent' },
  { name: 'Joseph', surname: 'Smith', alias: 'CD', occupation: 'agent' },
  { name: 'Peter', surname: 'Parker', alias: 'CD', occupation: 'agent' },
  { name: 'Charlie', surname: 'D Amelio', alias: 'CD', occupation: 'agent' },
  { name: 'Joseph', surname: 'Smith', alias: 'CD', occupation: 'agent' },
  { name: 'Peter', surname: 'Parker', alias: 'CD', occupation: 'agent' },
  { name: 'Charlie', surname: 'D Amelio', alias: 'CD', occupation: 'agent' },
  { name: 'Joseph', surname: 'Smith', alias: 'CD', occupation: 'agent' },
  { name: 'Peter', surname: 'Parker', alias: 'CD', occupation: 'agent' },
  { name: 'Charlie', surname: 'D Amelio', alias: 'CD', occupation: 'agent' },
  { name: 'Joseph', surname: 'Smith', alias: 'CD', occupation: 'agent' },
  { name: 'Peter', surname: 'Parker', alias: 'CD', occupation: 'agent' },
  { name: 'Charlie', surname: 'D Amelio', alias: 'CD', occupation: 'agent' },
  { name: 'Joseph', surname: 'Smith', alias: 'CD', occupation: 'agent' },
  { name: 'Peter', surname: 'Parker', alias: 'CD', occupation: 'agent' },
  { name: 'Charlie', surname: 'D Amelio', alias: 'CD', occupation: 'agent' },
  { name: 'Joseph', surname: 'Smith', alias: 'CD', occupation: 'agent' },
  { name: 'Peter', surname: 'Parker', alias: 'CD', occupation: 'agent' },
];
