export default [
  { name: 'Charlie', surname: 'D Amelio' },
  { name: 'Joseph', surname: 'Smith' },
  { name: 'Peter', surname: 'Parker' },
  { name: 'Charlie', surname: 'D Amelio' },
  { name: 'Joseph', surname: 'Smith' },
  { name: 'Peter', surname: 'Parker' },
  { name: 'Charlie', surname: 'D Amelio' },
  { name: 'Joseph', surname: 'Smith' },
  { name: 'Peter', surname: 'Parker' },
  { name: 'Charlie', surname: 'D Amelio' },
  { name: 'Joseph', surname: 'Smith' },
  { name: 'Peter', surname: 'Parker' },
  { name: 'Charlie', surname: 'D Amelio' },
  { name: 'Joseph', surname: 'Smith' },
  { name: 'Peter', surname: 'Parker' },
  { name: 'Charlie', surname: 'D Amelio' },
  { name: 'Joseph', surname: 'Smith' },
  { name: 'Peter', surname: 'Parker' }
];
